# Create an incremental tag on Github using SemVer https://semver.org: x.y.z

name: Release

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
<<<<<<< HEAD
        description: Release type
        options:
        - patch (x.y.Z)
        - minor (x.Y.z)
        - major (X.y.z)

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Tag for release

    steps:
      - name: Create tag as version for package on Packagist.org
        id: create-tag
        uses: GregoryGost/version-tagger@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          uselasttag: true
          releasetype: ${{ inputs.choice }}
=======
        description: "Release types: x.y.patch, x.minor.z, major.y.z"
        options:
        - patch
        - minor
        - major

jobs:
  release:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Tag for release
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Last version
      id: last-version
      run: echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"
    - name: debug
      run: echo ${{ steps.last-version.outputs.tag }}
    - name: Bump version
      id: bump-version
      uses: olegsu/semver-action@v1
      with:
        version: ${{ steps.last-version.outputs.tag }}
        bump: ${{ inputs.choice }}
    - name: Create tag as version for the package on Packagist.org
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git tag ${{ steps.bump-version.outputs.version }}
        git push origin ${{ steps.bump-version.outputs.version }}
>>>>>>> fix(workflow): workflow action version
